CREATE or replace TABLE sandbox.Raw.TenK_Projects AS 
SELECT
  Projects_id,
  data_retrieval_time,
  client,
  phase_name,
  project_state,
  owner_name,
  owner_id,
  updated_at,
  created_at,
  guid,
  ends_at,
  thumbnail,
  tag.value AS tags_value,
  tag.id AS tags_id,
  tags.paging.next AS tags_next,
  tags.paging.self AS tags_self,
  tags.paging.previous AS tags_previous,
  tags.paging.page AS tags_page,
  tags.paging.per_page AS tags_per_page,
  deleted_at,
  settings,
  timeentry_lockout,
  type,
  secureurl_expiration,
  description,
  secureurl,
  has_pending_updates,
  archived_at,
  project_code,
  starts_at,
  archived,
  use_parent_bill_rates,
  parent_id,
  project_state_id,
  name
FROM
  `sandbox.Landing.TenK_Projects`,
  UNNEST([tags]) AS tags
LEFT JOIN UNNEST(tags.data) AS tag
